# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "reka-whatsapp-confirm"
embedded = true
client_id = "bd6cc0fc0a82fbfd21020dda62d85f20"
application_url = "https://shopify.dev/apps/default-app-home"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[webhooks]
api_version = "2026-10"

[build]
automatically_update_urls_on_dev = true

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
